# Generated by Django 5.2.4 on 2025-07-31 23:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(max_length=300)),
                ('authors', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('categories', models.CharField(blank=True, max_length=200)),
                ('published_date', models.CharField(blank=True, max_length=20)),
                ('page_count', models.IntegerField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=10)),
                ('average_rating', models.FloatField(blank=True, null=True)),
                ('ratings_count', models.IntegerField(blank=True, null=True)),
                ('preview_link', models.URLField(blank=True)),
                ('info_link', models.URLField(blank=True)),
                ('topic_vector', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('ratings', models.FloatField(blank=True, null=True)),
                ('rating_level', models.CharField(blank=True, max_length=20)),
                ('difficulty_num', models.FloatField(blank=True, null=True)),
                ('students_enrolled', models.IntegerField(blank=True, null=True)),
                ('popularity', models.FloatField(blank=True, null=True)),
                ('platform', models.CharField(default='Coursera', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('topic_vector', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('channel', models.CharField(max_length=200)),
                ('published_at', models.DateTimeField()),
                ('difficulty', models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('topic_vector', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LearnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('highest_education', models.CharField(blank=True, max_length=100)),
                ('imd_band', models.CharField(blank=True, max_length=20)),
                ('age_band', models.CharField(blank=True, max_length=20)),
                ('avg_session_duration_min', models.FloatField(blank=True, null=True)),
                ('course_prop', models.FloatField(blank=True, null=True)),
                ('reading_prop', models.FloatField(blank=True, null=True)),
                ('video_prop', models.FloatField(blank=True, null=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('click', 'Click'), ('view', 'View'), ('like', 'Like'), ('bookmark', 'Bookmark'), ('rating', 'Rating'), ('complete', 'Complete')], max_length=50)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.book')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.course')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.learnerprofile')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.video')),
            ],
        ),
    ]
