# Generated by Django 5.2.4 on 2025-08-01 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='rating_level',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
