# Generated by Django 5.2.4 on 2025-08-05 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_course_rating_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learnerprofile',
            old_name='imd_band',
            new_name='preferred_format',
        ),
        migrations.AddField(
            model_name='learnerprofile',
            name='topic_interests',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
