# Generated by Django 5.2.4 on 2025-08-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_imd_band_learnerprofile_preferred_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='gbooks_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='book',
            name='isbn_13',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='book',
            name='thumbnail',
            field=models.URLField(blank=True),
        ),
    ]
