# Generated by Django 5.2.4 on 2025-09-04 21:50

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_enable_pgvector"),
    ]

    operations = [
        migrations.CreateModel(
            name='VectorizationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_tag', models.CharField(max_length=64, unique=True)),
                ('model_name', models.CharField(max_length=128)),
                ('vector_kind', models.CharField(choices=[('topic_distribution', 'topic_distribution'), ('embedding', 'embedding')], max_length=32)),
                ('dim', models.PositiveIntegerField(default=50)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('input_snapshot_hash', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'vectorization_run',
                'indexes': [models.Index(fields=['model_name'], name='vectorizati_model_n_9d64c9_idx'), models.Index(fields=['vector_kind'], name='vectorizati_vector__84caa0_idx')],
            },
        ),
        migrations.CreateModel(
            name='TopicVector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modality', models.CharField(choices=[('book', 'book'), ('course', 'course'), ('video', 'video')], max_length=16)),
                ('external_id', models.CharField(max_length=128)),
                ('vector', pgvector.django.vector.VectorField(dimensions=50)),
                ('dim', models.PositiveIntegerField(default=50)),
                ('model_name', models.CharField(max_length=128)),
                ('vector_kind', models.CharField(choices=[('topic_distribution', 'topic_distribution'), ('embedding', 'embedding')], max_length=32)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vectors', to='core.vectorizationrun')),
            ],
            options={
                'db_table': 'topic_vector',
                'indexes': [models.Index(fields=['modality'], name='topic_vecto_modalit_39e5a4_idx'), models.Index(fields=['model_name'], name='topic_vecto_model_n_f9b916_idx'), models.Index(fields=['vector_kind'], name='topic_vecto_vector__f4dc1e_idx'), pgvector.django.indexes.IvfflatIndex(fields=['vector'], lists=100, name='tv_vector_ivf_cos', opclasses=['vector_cosine_ops'])],
                'constraints': [models.UniqueConstraint(fields=('run', 'modality', 'external_id'), name='uniq_item_per_run')],
            },
        ),
    ]
