# Generated by Django 5.2.4 on 2025-09-05 12:19

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_vectorizationrun_topicvector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicvector',
            name='dim',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='topicvector',
            name='vector',
            field=pgvector.django.vector.VectorField(dimensions=30),
        ),
        migrations.AlterField(
            model_name='vectorizationrun',
            name='dim',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
