# Generated by Django 5.2.4 on 2025-09-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_topicvector_dim_alter_topicvector_vector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerprofile',
            name='format_model_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learnerprofile',
            name='format_prior_weight',
            field=models.FloatField(blank=True, default=0.3, null=True),
        ),
    ]
